public class ProductConfigWrapper {
    @AuraEnabled public String mic {get;set;}
    @AuraEnabled public String varient_character_mapping {get;set;}
    @AuraEnabled public String description {get;set;}
    @AuraEnabled public String uom {get;set;}
    @AuraEnabled public String quantitative {get;set;}
    @AuraEnabled public String qualitative {get;set;}
    @AuraEnabled public String olam_range {get;set;}
    @AuraEnabled public String customer_range {get;set;}
    @AuraEnabled public String category {get;set;}
}